[package]
name = "adaptive-card-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
schemafy = "0.6.0"
schemafy_core = "0.6.0"
serde = "1.0.219"
serde_json = "1.0.140"

[dev-dependencies]
expect-test = "1.5.1"
